version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: prisma-mysql-container
    environment:
      MYSQL_DATABASE: ${MYSQL_ID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - "${EXPOSE_DB_PORT}:3306"
    networks:
      - prisma-mysql-net
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

networks:
  prisma-mysql-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local